[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "trackedit"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "TeunHuijben", email = "teun.huijben@czbiohub.org" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = []

[project.urls]
Documentation = "https://github.com/TeunHuijben/trackedit#readme"
Issues = "https://github.com/TeunHuijben/trackedit/issues"
Source = "https://github.com/TeunHuijben/trackedit"

[tool.hatch.version]
path = "src/trackedit/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/trackedit tests}"

[tool.coverage.run]
source_pkgs = ["trackedit", "tests"]
branch = true
parallel = true
omit = [
  "src/trackedit/__about__.py",
]

[tool.coverage.paths]
trackedit = ["src/trackedit", "*/trackedit/src/trackedit"]
tests = ["tests", "*/trackedit/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
