[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "trackedit"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
keywords = []
authors = [
  { name = "TeunHuijben", email = "teun.huijben@czbiohub.org" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "mip >= 1.16rc0"
, "ultrack>=0.6.3,<0.7"]

[project.urls]
Documentation = "https://github.com/TeunHuijben/trackedit#readme"
Issues = "https://github.com/TeunHuijben/trackedit/issues"
Source = "https://github.com/TeunHuijben/trackedit"

[tool.hatch.version]
path = "trackedit/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:trackedit tests}"

[tool.coverage.run]
source_pkgs = ["trackedit", "tests"]
branch = true
parallel = true
omit = [
  "trackedit/__about__.py",
]

[tool.coverage.paths]
trackedit = ["trackedit", "*/trackedit/trackedit"]
tests = ["tests", "*/trackedit/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.pixi.project]
channels = ["conda-forge", "numba","gurobi","funkelab"]
platforms = ["linux-64", "win-64", "osx-arm64"]
preview = ["pixi-build"]

[tool.pixi.pypi-dependencies]
trackedit = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
higra = ">=0.6.12,<0.7"
numba = { version = ">=0.60.0,<0.61", channel = "numba" }
llvmlite = { version = ">=0.44.0,<0.45", channel = "numba" }
